developer_tag: morphvfx
auth_sub:
  secure: 0
  session: 1
  developer_key: AI39si57I1WXXFZSHlDFjrfUgBapS7DoJ0hPppuqgC2FY_vK-nUQ8Iw7lTUJTdqwSCstyIhSWBk-C9JI1DCQolrmVvTcj6xvLg
  client_key: And-Here-Goes-Your-Client-Key